// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmzlhnbkriagrchwochr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptemxobmJrcmlhZ3JjaHdvY2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjIyNzEsImV4cCI6MjA2NzAzODI3MX0.ba9H57or0r4avlyxswvOoUM12g6vdx5_ovLaHdfHz74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});